---
name: Bump version

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  bump-version:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    env:
      PR_LABELS: ${{ github.event.pull_request.labels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Fetch tags
        run: git fetch --depth=1 --tags

      - name: Bump version
        run: .github/scripts/bump_version.sh
